# Generated by Django 5.1.1 on 2024-10-14 06:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medikua',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100)),
                ('abizena', models.CharField(max_length=125)),
                ('jaiotze_data', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100)),
                ('abizena', models.CharField(max_length=125)),
                ('jaiotze_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Zitak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hasiera_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('bukaera_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('mediku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OsakidetzaAriketa.medikua')),
                ('paziente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OsakidetzaAriketa.paziente')),
            ],
        ),
    ]
